name: layoutgpt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hecacb30_2
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h95df7f1_0
  - mkl_fft=1.3.1=py38h8666266_1
  - mkl_random=1.2.2=py38h1abd341_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - numpy=1.24.3=py38h14f4228_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1t=h7f8727e_0
  - pip=23.0.1=py38h06a4308_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.16=h7a1cb2a_3
  - python_abi=3.8=2_cp38
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=67.8.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.6.3=pyha770c72_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - altair==5.0.1
    - antlr4-python3-runtime==4.9.3
    - async-timeout==4.0.2
    - attrdict==2.0.1
    - attrs==23.1.0
    - backports-zoneinfo==0.2.1
    - blinker==1.6.2
    - cachetools==5.3.1
    - certifi==2023.5.7
    - click==8.1.3
    - cmake==3.26.3
    - contourpy==1.0.7
    - cssutils==2.6.0
    - cycler==0.11.0
    - cython==0.29.35
    - decorator==5.1.1
    - dnspython==2.3.0
    - einops==0.6.1
    - filelock==3.12.0
    - fonttools==4.39.4
    - frozenlist==1.3.3
    - fsspec==2023.5.0
    - ftfy==6.1.1
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.31
    - glcontext==2.3.7
    - google-auth==2.19.1
    - google-auth-oauthlib==1.0.0
    - grpcio==1.54.2
    - huggingface-hub==0.15.1
    - imageio==2.31.0
    - imageio-ffmpeg==0.4.8
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - kornia==0.6.12
    - lazy-loader==0.2
    - lightning-utilities==0.8.0
    - lit==16.0.5.post0
    - markdown==3.4.3
    - markdown-it-py==2.2.0
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - mdurl==0.1.2
    - moderngl==5.8.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - multipledispatch==0.6.0
    - networkx==3.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - openai==0.27.8
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - packaging==23.1
    - pandas==2.0.2
    - parso==0.8.3
    - pillow==9.5.0
    - pkgutil-resolve-name==1.3.10
    - plyfile==0.9
    - prettytable==3.7.0
    - protobuf==3.20.3
    - pudb==2022.1.3
    - pyarrow==12.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydeck==0.8.1b0
    - pygments==2.15.1
    - pymongo==4.3.3
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrr==0.10.3
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - pytorch-lightning==2.0.2
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - regex==2023.6.3
    - requests-oauthlib==1.3.1
    - rich==13.4.1
    - rsa==4.9
    - safetensors==0.3.1
    - scikit-image==0.21.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - shapely==2.0.1
    - simple-3dviz==0.4.0
    - smmap==5.0.0
    - streamlit==1.23.1
    - sympy==1.12
    - tenacity==8.2.2
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.0
    - tensorboardx==2.6
    - test-tube==0.7.5
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - timm==0.9.2
    - tokenizers==0.13.3
    - toml==0.10.2
    - toolz==0.12.0
    - torch==2.0.1
    - torch-fidelity==0.3.0
    - torchmetrics==0.11.4
    - torchvision==0.15.2
    - tornado==6.3.2
    - tqdm==4.65.0
    - transformers==4.29.2
    - trimesh==3.22.0
    - triton==2.0.0
    - tzdata==2023.3
    - tzlocal==4.3
    - urllib3==1.26.16
    - urwid==2.1.2
    - urwid-readline==0.13
    - validators==0.20.0
    - watchdog==3.0.0
    - wcwidth==0.2.6
    - werkzeug==2.3.4
    - wxpython==4.2.0
    - yacs==0.1.8
    - yarl==1.9.2
    - zipp==3.15.0
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip